import { type Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Free sounds for game development',
  description: 'Generated by Next.js'
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout ({ children }: Props): JSX.Element {
  return (
    <html lang="en">
    <body>{children}</body>
    </html>
  )
}
